version: "3.8"

services:
  customers:
    build:
      context: ./
      target: builder
      dockerfile: Dockerfile.dev
    env_file: ./.env_file
    expose:
      - 8080
    labels:
      - "app=customers"
    environment:
      - ENV=dev
    volumes:
      - ${PWD}:/go/src/app
    stdin_open: true
    tty: true
  postgres-customers:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "pgdata_account:/var/lib/postgresql/data"
    command: ["postgres", "-c", "log_statement=all"]
volumes:
  pgdata_account:
